### PR TITLE
autocomplete bundle info on name if in worksheet

### PR DESCRIPTION
**Pull request by Raisins**
While doing `cl info ` if you start to type a name of a bundle it will autocomplete for you. Else assumes you are doing a `cl search` and just looking at any and all bundles since names repeat outside of your worksheet..  Need some discussion about what the UX flow should be. 

cl-info

issue: #1107

### CODE REVIEW

**Comment by percyliang** [comment]
Autocomplete for bundles shouldn't use 'cl search' because bundle names are not unique, so it's really confusing to do that.  Instead, just match on bundles in the current worksheet.  Eventually, we want this for other commands, the main one being 'cl run'.

**Comment by Raisins** [comment]
So the use case is only on bundles in the current work sheet. `cl info` would not be used to find/info on other bundles? 
I kept in if you do an empty tab complete or if you start with `0x...` and hit tab it's a generic look up while if you start a name and hit tab it is only on this worksheet.

**Comment by percyliang** [comment]
Yes, this is just to be consistent with the semantics of autocomplete
actually just filling out a prefix, not doing a general search given
keywords, which would be required if people actually wanted to find bundles.

We'll need a separate mechanism for search (typing in free-form keywords
and updating in real time), but that will be distinct from this
autocomplete.

**Comment by Raisins** [comment]
Cool, The end points for both types of search are set up. 
Will change `cl info` to use autocomplete with only in worksheet bundles. Which can use as a model for other commands in the future.

**Comment by Raisins** [comment]
Forcing worksheet on search on front end and codalab site backend. But in cli I am seeing `search -w worksheet` not respecting worksheet 
screen shot 2015-09-28 at 1 11 57 pm

**Comment by percyliang** [comment]
Search shouldn't depend on the current worksheet (right now).

**Comment by Raisins** [comment]
Changed to a worksheet look up similar to `cl ls`. Matches on name and only bundles in current worksheet. 
cl-info
A small bug left about name to uuid (hitting enter opens the wrong bundle info)

**Pull request merged**
