### PR TITLE
Feature/1335 update home page

### PR DESCRIPTION
**Pull request by FlavioAlexander**
New homepage

### CODE REVIEW

**Comment by percyliang** [comment]
That was merged faster than I could comment on!

The buttons should be labeled:
- Create an experiment! => Worksheets
- Join a challenge => Competitions

We should have more spacing between the worksheets and competitions.

Not all worksheets are created equal, so we don't just want to surface the most recent worksheets...there should be a filter and also randomize since there will be many matches.  This should be fixed before we deploy.

**Comment by FlavioAlexander** [comment]
@percyliang To make sure I understand:

* Currently we have "Create an Experiment!" It should be changed to "Create an experiment!" (only difference is "E" uppercase to lowercase) or do you want "Create an experiment! => Worksheets"?
* Same applies to Competitions
* I will add more space between worksheets and competitions
* For the last part, filtering requires a lot of engineering effort. P1 was to get a new homepage up and running. I could change my logic to display random worksheets, but filtering will need to wait for now.

Best,

Flavio

**Comment by percyliang** [comment]
On Thu, Oct 15, 2015 at 1:55 PM, Flavio Alexander <notifications@github.com>
wrote:

> @percyliang <https://github.com/percyliang> To make sure I understand:
>
>    - Currently we have "Create an Experiment!" It should be changed to
>    "Create an experiment!" (only difference is "E" uppercase to lowercase) or
>    do you want "Create an experiment! => Worksheets"?
>
>
Just "Worksheets"

>
>    - Same applies to Competitions
>    - I will add more space between worksheets and competitions
>    - For the last part, filtering requires a lot of engineering effort.
>    P1 was to get a new homepage up and running. I could change my logic to
>    display random worksheets, but filtering will need to wait for now.
>
> For now, let's just choose one of these worksheets at random and show it:

0x106abb3b47be492aa7387f528c943faa
0x66df55eda5054cbf9e173520c7b6ac3d
0x56dc93bcd3a647b197ad6e4b9d56f336
0xf26cd79d4d734287868923ad1067cf4c
0x269ef752f8c344a28383240f7bb2be9c
0x7f9151ec074f4f589e4d4786db7bb6de
0x8967960a7c644492974871ee60198401
0xc6edf0c9bec643ac9e74418bd6ad4136
0xfcace41fdeec45f3bc6ddf31107b829f

Remember to check that these exist (since they might not exist on other
instances off of codalab.org).

These are the executable papers on this website:
https://www.codalab.org/worksheets/0x9b6bb6fdd4aa4bf1b120300fd95f944a/

Later, we'll add functionality to dynamically pull the set of worksheets
(via the search functionality)

 -Percy

**Comment by FlavioAlexander** [comment]
@percyliang: Here's what I got so far, what do you think?

Responsive:
codalab_-_home-mobile
Full view:
codalab_-_home


As for hard coding the IDs, I think we'll add a new `settings` variable `FRONTPAGE_WORKSHEET_UUIDS` like so:

in `settings/base.py`:
```python
FRONTPAGE_WORKSHEET_UUIDS = (
    '0x106abb3b47be492aa7387f528c943faa',
    '0x66df55eda5054cbf9e173520c7b6ac3d',
    '0x56dc93bcd3a647b197ad6e4b9d56f336',
    '0xf26cd79d4d734287868923ad1067cf4c',
    '0x269ef752f8c344a28383240f7bb2be9c',
    '0x7f9151ec074f4f589e4d4786db7bb6de',
    '0x8967960a7c644492974871ee60198401',
    '0xc6edf0c9bec643ac9e74418bd6ad4136',
    '0xfcace41fdeec45f3bc6ddf31107b829f',
)
```

**Also, is there a function to grab the worksheets for this list of IDs? Or will we have to grab the list of all worksheets and filter on these?**

**Comment by kashizui** [comment]
The site looks great!

May I suggest a slightly more pastel version of the orange color on the buttons? Maybe something around #FFC266
screen shot 2015-10-16 at 12 19 05 pm

**Comment by percyliang** [comment]
+1

**Comment by FlavioAlexander** [comment]
@kashizui Thank you for the input :+1:

**Pull request merged**
