### PR TITLE
#1273 render worksheet title

### PR DESCRIPTION
**Pull request by pbhatnagar3**
#1273 

#### worksheet with a title

werwe

#### worksheet without a title
image

@percyliang @kashizui please review

### CODE REVIEW

**Comment by percyliang** [comment]
Could we render the title as the most prominent thing in place of the name
(a bit smaller than it is right now so we don't have too much wrapping),
and have the name underneath in a much smaller font, along with the owner?

**Comment by pbhatnagar3** [comment]
Yeah sure. Just saw this. I will make those changes as soon as I am done with dinner. :)

**Comment by pbhatnagar3** [comment]
The updated layout looks like the following:
new_layout

**Comment by kashizui** [comment]
Looks great! Did we want attribute names (e.g. "Owner: Codalab") in the sidebar as well?

**Comment by percyliang** [comment]
Looks good.  Two things:
- Make sure the title shows up in <title>...</title>
- Update the side panel to be consistent with the main page (might be even
wise to share code).  Only difference is to print out the uuid (because we
might be displaying a subworksheet).

**Comment by pbhatnagar3** [comment]
Updated the side_panel too. And <title>...</title> contains the title. @percyliang @kashizui please review.

**Comment by percyliang** [comment]
Is <title>...</title> actually set to worksheet.title?  Otherwise, LGTM.

**Comment by pbhatnagar3** [comment]
Yup. The line ``  {% block head_title %}{{worksheet_title}} -  Worksheet details{% endblock head_title %}`` in codalab/apps/web/templates/web/worksheets/detail.html takes care of it. I double checked the source of the rendered page and it is set.

**Comment by percyliang** [comment]
Ah, okay - thanks!

**Comment by kashizui** [comment]
LGTM!

**Pull request merged**
